### PR TITLE
Preparing for M1 chip macbook

### PR DESCRIPTION
**Pull request by SAGARSURI**
Relate to this issue #58

### CODE REVIEW

**Comment by om-ha** [comment]
Any update on this? @SAGARSURI @frencojobs 

```log
Invalid argument(s): Failed to load dynamic library '/Users/my_user/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib': dlopen(/Users/my_user/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib, 0x0001): tried: '/Users/my_user/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/executor_mac64.dylib' (no such file)
```

STR
```sh
fvm dart pub global list
fvm dart pub global activate derry
export PATH="$PATH":"$HOME/.pub-cache/bin"
derry build
```

**Comment by SAGARSURI** [comment]
> Any update on this? @SAGARSURI @frencojobs
> 
> ```
> Invalid argument(s): Failed to load dynamic library '/Users/my_user/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib': dlopen(/Users/my_user/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib, 0x0001): tried: '/Users/my_user/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/executor_mac64.dylib' (no such file)
> ```
> 
> STR
> 
> ```shell
> fvm dart pub global list
> fvm dart pub global activate derry
> export PATH="$PATH":"$HOME/.pub-cache/bin"
> derry build
> ```

@om-ha 
- First, check out my branch on your machine.
- Deactivate derry by running `dart pub global deactivate derry`
- From the terminal navigate to the root of this project.
- Run the following command:
`dart pub global activate -s path .`

Now you can use derry on M1

**Comment by SAGARSURI** [comment]
@om-ha 
I forgot to mention one step. You also need to rename the file `executor_mac_arm64.dylib` to `executor_mac64.dylib` before running the above command.

**Comment by tembamazingi** [comment]
Hi @SAGARSURI, after cloning your branch and following the other steps outlined, every time I try to run derry commands, they expect to run in the same directory I cloned your repo to and not the current project directory I am working in.

For example:

`✦ ❯ pwd
/Users/temba/Projects/Coatl

Coatl on  rumbo_web_journey_planner_dev [!+] via 🎯 v2.17.5
✦ ❯ derry generate .
No /Users/temba/Projects/derry/pubspec.lock file found, please run "dart pub get" first.

Coatl on  rumbo_web_journey_planner_dev [!+] via 🎯 v2.17.5
✦ ❯`

**Comment by frencojobs** [comment]
Hey everyone, [I'm back](https://frenco.dev/blog/i-am-back). I'm so sorry for being unresponsive for such a long time.

If you're still using derry, I just finished working on [v1.5](#69) that'll add support for M1 Macs. It contains a lot of code updates so I just asked a friend of mine to help me compile an ARM64 blob. I'll close this PR once it's released.

Thank you @SAGARSURI for the PR and for helping people with the workaround.

**Pull request closed without merging**
